// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacePark.Models;

namespace SpacePark.Migrations
{
    [DbContext(typeof(SpaceParkContext))]
    [Migration("20200921133122_Initialv2")]
    partial class Initialv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpacePark.Parkinglot", b =>
                {
                    b.Property<int>("ParkinglotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("SpaceshipID")
                        .HasColumnType("int");

                    b.HasKey("ParkinglotID");

                    b.HasIndex("SpaceshipID");

                    b.ToTable("Parkinglot");
                });

            modelBuilder.Entity("SpacePark.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpaceshipID")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.HasIndex("SpaceshipID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SpacePark.Spaceship", b =>
                {
                    b.Property<int>("SpaceshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpaceshipID");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("SpacePark.Parkinglot", b =>
                {
                    b.HasOne("SpacePark.Spaceship", "Spaceship")
                        .WithMany()
                        .HasForeignKey("SpaceshipID");
                });

            modelBuilder.Entity("SpacePark.Person", b =>
                {
                    b.HasOne("SpacePark.Spaceship", "CurrentShip")
                        .WithMany()
                        .HasForeignKey("SpaceshipID");
                });
#pragma warning restore 612, 618
        }
    }
}
